import type { ItemDef, NpcId, TradeRecipe } from "./types";

export const SHELF_SLOTS = 12;

export const ITEMS: Record<string, ItemDef> = {
  white_cockle: {
    id: "white_cockle",
    name: "White Cockle",
    kind: "shell",
    rarity: "common",
    description: "A tidy little fan of white, still warm from the sun-baked sand.",
    color: 0xf4efe6,
    accent: 0xe8d7c4,
  },
  striped_whelk: {
    id: "striped_whelk",
    name: "Striped Whelk",
    kind: "shell",
    rarity: "common",
    description: "Cocoa stripes spiral toward a point as sharp as a secret.",
    color: 0xd9b48a,
    accent: 0x6b3f2a,
  },
  tiny_cowrie: {
    id: "tiny_cowrie",
    name: "Tiny Cowrie",
    kind: "shell",
    rarity: "common",
    description: "Small enough to tuck behind Eva's ear. Glossy as a drop of milk.",
    color: 0xfff7d6,
    accent: 0xf0c4a0,
  },
  blue_limpet: {
    id: "blue_limpet",
    name: "Blue Limpet",
    kind: "shell",
    rarity: "common",
    description: "A shallow cap of sea-blue, the colour of noon shallows.",
    color: 0x7ec8e8,
    accent: 0x3a7ca5,
  },
  sunset_scallop: {
    id: "sunset_scallop",
    name: "Sunset Scallop",
    kind: "shell",
    rarity: "uncommon",
    description: "Ridges blush from peach to rose, as if it kept a whole evening.",
    color: 0xff9b73,
    accent: 0xffd29a,
    glow: 0xff8a5b,
  },
  spiral_turban: {
    id: "spiral_turban",
    name: "Spiral Turban",
    kind: "shell",
    rarity: "uncommon",
    description: "A green-gold turban that looks like it is still spinning.",
    color: 0x7bc47a,
    accent: 0xe7d27a,
    glow: 0x7bc47a,
  },
  pearl_mussel: {
    id: "pearl_mussel",
    name: "Pearl Mussel",
    kind: "shell",
    rarity: "uncommon",
    description: "Inside: a quiet moonlight. Outside: the colour of wet slate.",
    color: 0x6d7c8b,
    accent: 0xf3f0ea,
    glow: 0xdce9f4,
  },
  candy_conch: {
    id: "candy_conch",
    name: "Candy Conch",
    kind: "shell",
    rarity: "uncommon",
    description: "Pink and cream swirls. Mallow would call it a pastry of the sea.",
    color: 0xffb3c7,
    accent: 0xfff0e4,
    glow: 0xff9bb8,
  },
  moon_nautilus: {
    id: "moon_nautilus",
    name: "Moon Nautilus",
    kind: "shell",
    rarity: "rare",
    description: "Chambers like a silver staircase. It hums if you hold it just so.",
    color: 0xdbe7ff,
    accent: 0x8aa4d6,
    glow: 0x9bb7ff,
  },
  rainbow_abalone: {
    id: "rainbow_abalone",
    name: "Rainbow Abalone",
    kind: "shell",
    rarity: "rare",
    description: "An inner sea of oil-slick colour. Every tilt is a new weather.",
    color: 0x5ecfc0,
    accent: 0xd46bdc,
    glow: 0x7b6cff,
  },
  star_sand_dollar: {
    id: "star_sand_dollar",
    name: "Star Sand Dollar",
    kind: "shell",
    rarity: "rare",
    description: "Five petals of pale gold with a star pressed into the heart.",
    color: 0xf3e2b3,
    accent: 0xd4b36a,
    glow: 0xffe08a,
  },
  heart_conch: {
    id: "heart_conch",
    name: "Heart Conch of the Tide",
    kind: "shell",
    rarity: "legendary",
    description: "Warm as a held hand. Legend says it remembers every kindness.",
    color: 0xff5d7a,
    accent: 0xffd36a,
    glow: 0xff7aa0,
  },
  prismatic_spiral: {
    id: "prismatic_spiral",
    name: "Prismatic Spiral",
    kind: "shell",
    rarity: "legendary",
    description: "Light climbs its stairs and comes down as music you can almost hear.",
    color: 0xb48cff,
    accent: 0x7ef0d8,
    glow: 0xd9a5ff,
  },

  smooth_pebble: {
    id: "smooth_pebble",
    name: "Smooth Pebble",
    kind: "rock",
    rarity: "common",
    description: "River-round and polite. The sort of stone that likes pockets.",
    color: 0x9aa7b2,
    accent: 0xc5cdd4,
  },
  beach_glass: {
    id: "beach_glass",
    name: "Beach Glass",
    kind: "rock",
    rarity: "common",
    description: "A sip of old bottle, frosted by years of polite waves.",
    color: 0x88d4c4,
    accent: 0xe7fff8,
  },
  striped_agate: {
    id: "striped_agate",
    name: "Striped Agate Chip",
    kind: "rock",
    rarity: "common",
    description: "Tiny bands of rust and cream, like a map of very old weather.",
    color: 0xc47a4a,
    accent: 0xf0d9b5,
  },
  basalt_bead: {
    id: "basalt_bead",
    name: "Basalt Bead",
    kind: "rock",
    rarity: "common",
    description: "Dark as a sleeping whale, with a single pale fleck for an eye.",
    color: 0x3d4450,
    accent: 0x8b93a1,
  },
  rose_quartz: {
    id: "rose_quartz",
    name: "Rose Quartz",
    kind: "rock",
    rarity: "uncommon",
    description: "A blush you can hold. Soft light lives in its corners.",
    color: 0xff9ab5,
    accent: 0xffd0dc,
    glow: 0xffb3c7,
  },
  sea_granite: {
    id: "sea_granite",
    name: "Sea-worn Granite",
    kind: "rock",
    rarity: "uncommon",
    description: "Salt has combed sparkles through the grey. Pebble would lecture.",
    color: 0xa8b0ae,
    accent: 0xe8dcc8,
    glow: 0xc5d0cc,
  },
  amber_droplet: {
    id: "amber_droplet",
    name: "Amber Droplet",
    kind: "rock",
    rarity: "uncommon",
    description: "A bead of trapped afternoon. Warm even in shade.",
    color: 0xf0a020,
    accent: 0xffe08a,
    glow: 0xffb347,
  },
  moss_agate: {
    id: "moss_agate",
    name: "Moss Agate",
    kind: "rock",
    rarity: "uncommon",
    description: "A forest froze inside this stone and never minded.",
    color: 0x6fbf8a,
    accent: 0xd5f0c8,
    glow: 0x7bc47a,
  },
  starstone: {
    id: "starstone",
    name: "Starstone",
    kind: "rock",
    rarity: "rare",
    description: "Pinpricks of white fire. Look too long and you'll miss the tide.",
    color: 0x2c2158,
    accent: 0xf4f1ff,
    glow: 0xb48cff,
  },
  tide_crystal: {
    id: "tide_crystal",
    name: "Tide Crystal",
    kind: "rock",
    rarity: "rare",
    description: "Clear as a promise. It fogs over when a storm is thinking.",
    color: 0xaee6ff,
    accent: 0xffffff,
    glow: 0x7ec8f8,
  },
  ember_geode: {
    id: "ember_geode",
    name: "Ember Geode",
    kind: "rock",
    rarity: "rare",
    description: "Crack the dull rind in your mind: a cave of orange stars.",
    color: 0x6b3f2a,
    accent: 0xff7a3a,
    glow: 0xff8a3d,
  },
  dawn_opal: {
    id: "dawn_opal",
    name: "Dawn Opal",
    kind: "rock",
    rarity: "legendary",
    description: "Morning, bottled. Eva's tiara seems to lean toward it.",
    color: 0xffc2d4,
    accent: 0x9be7ff,
    glow: 0xffd6e8,
  },
  wind_tear: {
    id: "wind_tear",
    name: "Wind's Tear",
    kind: "rock",
    rarity: "legendary",
    description: "A celestine drop said to fall from the sail of a sky-boat.",
    color: 0x7ef0d8,
    accent: 0xf4ffe8,
    glow: 0x7ef0d8,
  },

  knitted_cushion: {
    id: "knitted_cushion",
    name: "Mallow's Cushion",
    kind: "decor",
    rarity: "uncommon",
    description: "Lopsided on purpose. Smells faintly of meadow and biscuits.",
    color: 0xf4c6d7,
    accent: 0xfff6ea,
  },
  wool_lantern: {
    id: "wool_lantern",
    name: "Wool Lantern",
    kind: "decor",
    rarity: "uncommon",
    description: "A paper lantern in a knitted cozy. Ridiculous. Perfect.",
    color: 0xffe08a,
    accent: 0xf28b82,
  },
  flower_stool: {
    id: "flower_stool",
    name: "Flower Stool",
    kind: "decor",
    rarity: "uncommon",
    description: "A round seat with painted petals. It makes the floor cheerier.",
    color: 0x7bc47a,
    accent: 0xffd36a,
  },
  hanging_mobile: {
    id: "hanging_mobile",
    name: "Shell Mobile",
    kind: "decor",
    rarity: "rare",
    description: "Coral's work: shells that turn and gossip in the draft.",
    color: 0x7ec8e8,
    accent: 0xffb3c7,
  },
  tropical_rug: {
    id: "tropical_rug",
    name: "Tropical Rug",
    kind: "decor",
    rarity: "uncommon",
    description: "Woven palm and sunset thread. Bare feet required.",
    color: 0xe23a3a,
    accent: 0xf2c14e,
  },
  captain_lantern: {
    id: "captain_lantern",
    name: "Captain's Lantern",
    kind: "decor",
    rarity: "rare",
    description: "Brine swears it once spotted a ghost ship. It spotted a duck.",
    color: 0xc48a4a,
    accent: 0xffd36a,
  },
  sea_chart: {
    id: "sea_chart",
    name: "Chart of Quiet Waters",
    kind: "decor",
    rarity: "rare",
    description: "A map with a new X that wasn't there yesterday.",
    color: 0xf0d9b5,
    accent: 0x3a7ca5,
  },
  geology_book: {
    id: "geology_book",
    name: "Pebble's Field Notes",
    kind: "decor",
    rarity: "rare",
    description: "Scribbles, stars, and one drawing of Eva labelled 'specimen: friend'.",
    color: 0x6fbf8a,
    accent: 0xf4efe6,
  },
  potted_clover: {
    id: "potted_clover",
    name: "Potted Clover",
    kind: "decor",
    rarity: "common",
    description: "A hopeful little pot. Water it with attention.",
    color: 0x4f9d5c,
    accent: 0xc48a4a,
  },
  tea_set: {
    id: "tea_set",
    name: "Island Tea Set",
    kind: "decor",
    rarity: "uncommon",
    description: "Two cups. One for Eva, one for whoever wanders in.",
    color: 0xfff6ea,
    accent: 0x7ec8e8,
  },
  knitted_blanket: {
    id: "knitted_blanket",
    name: "Meadow Blanket",
    kind: "decor",
    rarity: "rare",
    description: "Mallow's baby-blanket stitch, scaled up for a chick who sails.",
    color: 0xf4c6d7,
    accent: 0x7ec8e8,
  },
  heart_pillow: {
    id: "heart_pillow",
    name: "Heart Pillow",
    kind: "decor",
    rarity: "rare",
    description: "A plump pink heart. It knows when you come home.",
    color: 0xe56b9e,
    accent: 0xfff6ea,
  },
  specimen_jar: {
    id: "specimen_jar",
    name: "Specimen Jar",
    kind: "decor",
    rarity: "rare",
    description: "Pebble labelled it 'friend-shaped'. The jar is empty. That's the point.",
    color: 0x9ed96a,
    accent: 0xf4efe6,
  },
  stall_banner: {
    id: "stall_banner",
    name: "Stall Banner",
    kind: "decor",
    rarity: "rare",
    description: "Coral painted a tiny red boat on it. The boat is winking.",
    color: 0xe23a3a,
    accent: 0xf2c14e,
  },
  helm_wheel: {
    id: "helm_wheel",
    name: "Spare Helm",
    kind: "decor",
    rarity: "rare",
    description: "Brine swears this wheel once steered a cloud. It steers a cottage now.",
    color: 0x8a5a32,
    accent: 0xc48a4a,
  },
};

export const STARTING_DECOR = ["potted_clover"];

export type IslandBiome = "home" | "meadow" | "stone" | "harbor" | "palm" | "reef" | "rocks";

export type IslandDef = {
  id: string;
  name: string;
  x: number;
  z: number;
  radius: number;
  height: number;
  seed: number;
  biome: IslandBiome;
  npc?: NpcId;
  discovery: string;
};

export const ISLANDS: IslandDef[] = [
  {
    id: "home",
    name: "Home Isle",
    x: 0,
    z: 0,
    radius: 56,
    height: 8.8,
    seed: 11,
    biome: "home",
    discovery: "Home Isle — the kettle island, the coming-back place.",
  },
  {
    id: "meadow",
    name: "Meadow Isle",
    x: -124,
    z: 82,
    radius: 50,
    height: 7.6,
    seed: 22,
    biome: "meadow",
    npc: "mallow",
    discovery: "Meadow Isle — where the grass hums and Mallow keeps the kettle on.",
  },
  {
    id: "stone",
    name: "Stone Isle",
    x: 132,
    z: 70,
    radius: 50,
    height: 11.4,
    seed: 33,
    biome: "stone",
    npc: "pebble",
    discovery: "Stone Isle — old arches, older opinions, and Pebble's library.",
  },
  {
    id: "harbor",
    name: "Brineharbor",
    x: -70,
    z: -128,
    radius: 48,
    height: 5.2,
    seed: 44,
    biome: "harbor",
    npc: "brine",
    discovery: "Brineharbor — ropes, stories, and a boat that has heard them all.",
  },
  {
    id: "palm",
    name: "Coral Cay",
    x: 116,
    z: -104,
    radius: 52,
    height: 6.2,
    seed: 55,
    biome: "palm",
    npc: "coral",
    discovery: "Coral Cay — colour enough to startle a rainbow.",
  },
  {
    id: "reef",
    name: "Whisper Reef",
    x: 14,
    z: 168,
    radius: 26,
    height: 3.4,
    seed: 66,
    biome: "reef",
    discovery: "Whisper Reef — a secret the tide almost kept.",
  },
  {
    id: "lookout",
    name: "Lookout Stack",
    x: -168,
    z: -28,
    radius: 18,
    height: 12.2,
    seed: 77,
    biome: "rocks",
    discovery: "Lookout Stack — a steep hat of stone in the wide blue.",
  },
];

export type NpcDef = {
  id: NpcId;
  name: string;
  species: string;
  island: string;
  color: number;
  accent: number;
  personality: string;
  greeting: string[];
  chat: string[];
  warm: string[];
  close: string[];
  nightLine: string;
  questTrade: string;
  questOpen: string;
  questHint: string;
  questDone: string;
  pip: string;
  trades: TradeRecipe[];
};

export const NPCS: Record<NpcId, NpcDef> = {
  mallow: {
    id: "mallow",
    name: "Mallow",
    species: "sheep",
    island: "meadow",
    color: 0xfff6ea,
    accent: 0xf4c6d7,
    personality: "A plump cream sheep who speaks in slow, warm ellipses and believes most problems can be knitted smaller.",
    greeting: [
      "Oh… hello, little chickadee. The kettle noticed you before I did.",
      "Eva… you brought the smell of salt in with you. Sit. Or don't. The grass is a chair too.",
    ],
    chat: [
      "I count waves instead of sheep, some evenings… they never all land.",
      "If you find a scallop the colour of sunset, I'll knit it a cousin.",
      "Your boat is very brave. Red things often are.",
      "Meadow Isle is west of the kettle island. You found me. The kettle is smug.",
    ],
    warm: [
      "Eva. The grass stood up when it heard your boat. Sit. I've saved the soft patch.",
      "You keep coming back. That's a kind of knitting, too.",
    ],
    close: [
      "Little chickadee. If the sea ever feels too wide, there is always a cup here with your name on the steam.",
      "I started a blanket with a red boat in it. The boat keeps sailing off the edge. Like someone I know.",
    ],
    nightLine: "Shh… the yarn is dreaming. So am I, mostly.",
    questTrade: "mallow-lantern",
    questOpen: "If you ever find a candy conch — pink as a pastry — I'll knit a baby blanket around the idea of you.",
    questHint: "Candy conches hide in the meadow grass. They look like sweets the tide forgot.",
    questDone: "The blanket's in your satchel. Put it somewhere the morning can find it.",
    pip: "🧶",
    trades: [
      {
        id: "mallow-cushion",
        want: [{ item: "striped_whelk", count: 2 }],
        give: { item: "knitted_cushion", count: 1 },
        once: true,
        label: "Trade 2 striped whelks for a cushion",
        success: "I… may have added a spare heart into the stitches. Put it on your shelf at home. A house should remember its guests.",
      },
      {
        id: "mallow-lantern",
        want: [{ item: "candy_conch", count: 1 }],
        give: { item: "wool_lantern", count: 1 },
        once: true,
        needFriend: 1,
        label: "Trade a candy conch for a wool lantern",
        success: "Now your house can blush after dark… that's all I wanted.",
      },
      {
        id: "mallow-stool",
        want: [{ item: "sunset_scallop", count: 1 }],
        give: { item: "flower_stool", count: 1 },
        once: true,
        needFriend: 2,
        label: "Trade a sunset scallop for a flower stool",
        success: "A seat for tiny brave bones. Tea optional. Tea recommended.",
      },
      {
        id: "mallow-blanket",
        want: [{ item: "tiny_cowrie", count: 3 }],
        give: { item: "knitted_blanket", count: 1 },
        once: true,
        needFriend: 2,
        label: "Trade 3 tiny cowries for a meadow blanket",
        success: "Wrap up when the wind tells stories. The blanket already knows the ending.",
      },
      {
        id: "mallow-pillow",
        want: [{ item: "heart_conch", count: 1 }],
        give: { item: "heart_pillow", count: 1 },
        once: true,
        needFriend: 3,
        label: "Show Mallow the Heart Conch",
        success: "Oh. Oh, Eva. I knitted a pillow that can almost hold that. Almost.",
      },
    ],
  },
  pebble: {
    id: "pebble",
    name: "Pebble",
    species: "frog",
    island: "stone",
    color: 0x6fbf8a,
    accent: 0x3d6b4f,
    personality: "A scholarly frog in round glasses who classifies everything, including feelings, and gets squeaky when a specimen is rare.",
    greeting: [
      "Ah! Field operative Eva. Have you brought lithic gossip?",
      "Mind the notes. Some of them are rocks. Some of the rocks are notes. It's a system.",
    ],
    chat: [
      "A smooth pebble is not 'just' a pebble. It is a long argument with water, and the water won kindly.",
      "Starstone is not from this sea. I have a theory. It involves a very clumsy constellation.",
      "Your tiara — relic? Crown? Fashion? I have three labels and no courage to ask.",
    ],
    warm: [
      "Field operative Eva, returning with data. Also with friendship. I have a column for that now.",
      "I reclassified you from 'visitor' to 'recurring phenomenon'. The library approved.",
    ],
    close: [
      "If the starstone ever feels lonely, bring it here. I talk to rocks. They talk back. Slowly.",
      "Specimen: friend. Status: verified. Please do not file yourself under 'lost'.",
    ],
    nightLine: "The archives close at moonrise. I do not. The archives and I are negotiating.",
    questTrade: "pebble-notes",
    questOpen: "If you find a starstone — not from this sea — I must classify it. I have three labels and no specimen.",
    questHint: "Starstone sits on the high spine of Stone Isle. It looks like a clumsy constellation landed.",
    questDone: "Citation complete. My field notes are yours. Don't eat the diagrams.",
    pip: "🪨",
    trades: [
      {
        id: "pebble-appraise",
        want: [{ item: "striped_agate", count: 1 }],
        give: { treats: 3 },
        label: "Let Pebble appraise a striped agate",
        success: "Banded chalcedony, beach-tumbled, grade: charming. Treats for the courier.",
      },
      {
        id: "pebble-notes",
        want: [{ item: "starstone", count: 1 }],
        give: { item: "geology_book", count: 1 },
        once: true,
        needFriend: 1,
        label: "Show Pebble a starstone",
        success: "I— I need to sit down. On a book. Take my field notes. You've earned a citation, Eva.",
      },
      {
        id: "pebble-agate",
        want: [{ item: "rose_quartz", count: 1 }, { item: "smooth_pebble", count: 1 }],
        give: { item: "moss_agate", count: 1 },
        once: true,
        needFriend: 2,
        label: "Trade rose quartz & a pebble for moss agate",
        success: "A forest, fossilised in patience. Don't put it in soup. I've checked. For science.",
      },
      {
        id: "pebble-jar",
        want: [{ item: "tide_crystal", count: 1 }],
        give: { item: "specimen_jar", count: 1 },
        once: true,
        needFriend: 3,
        label: "Show Pebble a tide crystal",
        success: "I'm putting this in a jar labelled 'proof that Eva exists'. The jar is mostly feelings.",
      },
    ],
  },
  coral: {
    id: "coral",
    name: "Coral",
    species: "parrot",
    island: "palm",
    color: 0xe23a3a,
    accent: 0xf2c14e,
    personality: "A loud, kind parrot merchant who rhymes when excited and believes a fair trade is a kind of music.",
    greeting: [
      "Awk! If it isn't the chick with the cherry boat! Come to haggle, gaggle, or gawk?",
      "Eva! The stall missed your little feet. What glitter did the tide misplace today?",
    ],
    chat: [
      "I don't sell maps. I sell moods. Maps are Brine's racket.",
      "Rare shells want to be seen. That's why they sparkle like gossips.",
      "If you've treats, I've rugs. If you've rugs, you've taste.",
    ],
    warm: [
      "Awk! Regular customer! That's a song. That's a stall with a heartbeat.",
      "Eva! I saved you the sparkliest gossip. It cost me nothing. That's how you know it's good.",
    ],
    close: [
      "If the stall ever feels too loud, you can sit on the crate and be the quiet. I'll sell around you.",
      "Fair trade is a kind of music. You, chick, are in the chorus now.",
    ],
    nightLine: "Shop's shut! Dreams are running a two-for-one. Awk. That was a joke. Mostly.",
    questTrade: "coral-mobile",
    questOpen: "Bring me a rainbow abalone and I'll hang it in the stall window. Colour like that wants an audience.",
    questHint: "Rainbow abalone loves the warm sand of Coral Cay. It gossips in oil-slick light.",
    questDone: "The window's showing off. Take the mobile — let your cottage gossip too.",
    pip: "🪶",
    trades: [
      {
        id: "coral-treats",
        want: [{ item: "white_cockle", count: 2 }],
        give: { treats: 5 },
        label: "Sell 2 white cockles for 5 treats",
        success: "Clink-clink! Treats for the brave. Don't eat them all before breakfast. Do, actually.",
      },
      {
        id: "coral-mobile",
        want: [{ item: "rainbow_abalone", count: 1 }],
        give: { item: "hanging_mobile", count: 1 },
        once: true,
        needFriend: 1,
        label: "Trade a rainbow abalone for a mobile",
        success: "I'll miss that colour. Hang it where the draft can brag.",
      },
      {
        id: "coral-rug",
        want: [{ item: "blue_limpet", count: 1 }],
        give: { item: "tropical_rug", count: 1, treats: -6 },
        once: true,
        needFriend: 2,
        label: "Trade a blue limpet + 6 treats for a rug",
        success: "A floor worth taking shoes off for. You don't wear shoes. Even better!",
      },
      {
        id: "coral-banner",
        want: [{ item: "star_sand_dollar", count: 1 }],
        give: { item: "stall_banner", count: 1 },
        once: true,
        needFriend: 3,
        label: "Trade a star sand dollar for a stall banner",
        success: "I painted your boat on it. Tiny. Winking. Don't tell the boat, it'll get vain.",
      },
    ],
  },
  brine: {
    id: "brine",
    name: "Captain Brine",
    species: "otter",
    island: "harbor",
    color: 0x8b5a3c,
    accent: 0xc48a4a,
    personality: "A stocky otter in a too-small captain's hat who tells enormous sea stories that are 40% true and 100% affectionate.",
    greeting: [
      "Aye, there's the little admiral. Wind treating you fair?",
      "Eva! I was just telling the dock about the time I arm-wrestled a squid. The dock is a good listener.",
    ],
    chat: [
      "Keep your spyglass handy. Pretty things hide in the corners of the sea on purpose.",
      "There's a reef due north that doesn't like to be found. That's how you know it's worth it.",
      "Your boat's heart on the bow? That's not decoration. That's a promise. I should know. I paint promises badly.",
      "Lookout Stack wears a steep hat west of home. Climb it. Look. The sea likes to be seen seeing.",
    ],
    warm: [
      "Aye, the little admiral. The dock asked after you. I told it you'd be along.",
      "Wind treating you fair? If not, call it to your bow. That's not cheating. That's manners.",
    ],
    close: [
      "If I ever don't come back from a story, check the hammock first. Then the sea. Then the hammock again.",
      "You're in the logbook now, Eva. Not as cargo. As crew. Tiny crew. Best crew.",
    ],
    nightLine: "Lantern's low. Even captains snore. Don't tell the tide.",
    questTrade: "brine-chart",
    questOpen: "Bring a pearl mussel and I'll give you a chart. X marks a whisper due north — a reef that doesn't like to be found.",
    questHint: "Pearl mussels like the quiet water around Brineharbor. Inside: moonlight. Outside: wet slate.",
    questDone: "Unfold it when the sea feels large. Sail north till the water turns shy. And Eva — come back.",
    pip: "⚓",
    trades: [
      {
        id: "brine-chart",
        want: [{ item: "pearl_mussel", count: 1 }],
        give: { item: "sea_chart", count: 1 },
        once: true,
        label: "Trade a pearl mussel for a sea chart",
        success: "X marks a whisper. Sail north till the water turns shy. Unfold the chart whenever the horizon gets ideas. And Eva — come back, that's an order dressed as a wish.",
      },
      {
        id: "brine-tea",
        want: [{ item: "beach_glass", count: 1 }],
        give: { item: "tea_set", count: 1 },
        once: true,
        needFriend: 1,
        label: "Trade beach glass for a tea set",
        success: "Won it off a gull in a staring contest. The gull blinked. Honourable.",
      },
      {
        id: "brine-lantern",
        want: [{ item: "moon_nautilus", count: 1 }],
        give: { item: "captain_lantern", count: 1 },
        once: true,
        needFriend: 2,
        label: "Trade a moon nautilus for a lantern",
        success: "Used to hang this on the prow. She's yours. May she gossip about safe harbors.",
      },
      {
        id: "brine-helm",
        want: [{ item: "wind_tear", count: 1 }],
        give: { item: "helm_wheel", count: 1 },
        once: true,
        needFriend: 3,
        label: "Show Brine a Wind's Tear",
        success: "Aye. That's a sky-drop. Take the spare helm. Cottage could use a little steering.",
      },
    ],
  },
};

export const SLEEP_LINES = [
  "Eva dreams of shells that sing when the tide turns.",
  "Somewhere, a boat heart beats in time with a chick heart.",
  "The islands shuffle their treasures like a kind dealer.",
  "Mallow knits a cloud and accidentally a weather.",
  "Pebble files the moon under 'pending'.",
  "Brine's chart grows a new X while nobody is looking.",
  "Coral prices the sunrise and decides it isn't for sale.",
];

export function rarityRank(r: ItemDef["rarity"]): number {
  return { common: 0, uncommon: 1, rare: 2, legendary: 3 }[r];
}
